#opacity settings
active-opacity = 0.90;
inactive-opacity = 0.85;

#fading settings
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.04;
fade-delta = 10;

backend = "glx";
vsync = true;

corner-radius = 12;
rounded-corners-exclude = [
  "class_g = 'i3-frame'",
  "class_g = 'Polybar'"
];

# Enable blur
blur-method = "dual_kawase";
blur-strength = 14;  # adjust to your taste





